### PR TITLE
[ADD] hide analytic account if the team doesn't have the option to Al…

### PR DESCRIPTION
**Pull request by JorgeQuinteros**
…low Timesheet

### CODE REVIEW

**Comment by EDallas89** [comment]
It is not a bug so it's a ADD not a FIX

**Comment by JorgeQuinteros** [comment]
> It is not a bug so it's a ADD not a FIX

Fixed :+1:

**Review by EDallas89 — APPROVED** [review]
Technical review

**Review by oscars8a — COMMENTED** [review]
Perfect

**Pull request merged**
